[package]
name = "jsonm"
version = "0.1.0"
authors = ["Andrew Nester <andrew.nester.dev@gmail.com>"]
repository = "https://github.com/andrewnester/rust-jsonm"
license = "MIT"
description = "jsonm implementation port for Rust."

[dependencies]
serde_json = "1.0"
serde = "1.0.79"
regex = "1"